---
name: Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    strategy:
      max-parallel: 3
      matrix:
        goos: [linux]
        goarch: [amd64]
        go-version: [ 1.20.4 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get Tag
        uses: olegtarasov/get-tag@v2.1.2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}
      - name: Publish Docker Image
        run: make docker-publish
      - name: Release Binary
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: ${{ matrix.go-version }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: "make build-release"
          binary_name: "smartctl_exporter"
          extra_files: LICENSE README.md
